### ISSUE TITLE
Input and Error on Web App

### ISSUE THREAD

**Issue by danphillips28** [BNadel/GEDIT#1]
Dear Dr Nadel,

Thank you for making GEDIT. I'm a beginner bioinformatician and my PI has asked me to try to assess how well a cell-splitting experiment has worked using some RNA-Seq data. I plan on using the GEDIT web tool for simplicity.

I just tried for the first time and received an error;

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

My input file is a (2.3MB, 15988 x 9) tab-seperated csv file, gene symbols in the first column and then average raw counts in the other columns, each representing a (hopefully) single cell-type population - but this is what I'd like to confirm. I used the Human Skin Signatures Reference and left everything else as default. Any help?

Best wishes,
Daniel

![image](https://user-images.githubusercontent.com/66078614/129380439-53071047-2663-43a8-bb93-cd5d4babd1c0.png)

**Comment by BNadel** [comment]
Hi Dan,

I hope you are well!

Can you send me the input file, please? I will see if I can reproduce the
problem

Best,
Brian

**Comment by danphillips28** [comment]
For anyone reading, I emailed Brian and the issue was resolved by the discovery of weird characters in the header line (â€œGeneâ€). Not sure how they got in there, but removing them and changing so as to appear in the screenshot did the trick. 

Thanks Brian!
