### ISSUE TITLE
Is it allowed to use single cell reference for microarray data deconvolution?

### ISSUE THREAD

**Issue by Pentayouth** [BNadel/GEDIT#3]
Dear Brian Nadel,

I wonder if a combination of reference and mixture from different platform practicable? If it is, anything to take care of when preprocessing the data?

For example,
microarray reference (e.g. LM22) for bulk RNA-seq,
single-cell RNAseq reference (e.g. 10X immune) for microarray data

Any suggestion is highly appreciated!

Best regards,
Wang

**Comment by BNadel** [comment]
Hello Wang,

While it varies on a case-by-case basis, combining RNA-seq + microarray
often gives inaccurate results. An RNA-seq dataset is best paired with an
RNA-seq reference, and a microarray dataset is best paired with a
microarray reference. When using microarrays for both, mixing models is
less than ideal but usually works out alright. E.g. Illumina microarray
reference combined with Affymetrix microarray mixture is probably okay.

Best,
Brian

**Comment by Pentayouth** [comment]
Dear Brian Nadel,

Thanks for your prompt response!

Besides, I would like to ask the correct way to generate custom scRNA-seq signature? Currently I calculate averaged expression across cells of the same cell type and perform NO log normalize.

Best regards,
Wang

**Comment by BNadel** [comment]
Yes, that is the correct way
